force-app/main/default/objects/Custom_Task__c/Custom_Task__c.object-meta.xml
<CustomObject>
    <label>Custom Task</label>
    <nameField>
        <label>Custom Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Task__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Name of the project to which the resource project linked to the task belongs.</description>
    <formula>Resource_Project__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Task__c/fields/Registered_Hours__c.field-meta.xml
<CustomField>
    <fullName>Registered_Hours__c</fullName>
    <label>Registered Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Task__c/fields/Required_Hours__c.field-meta.xml
<CustomField>
    <fullName>Required_Hours__c</fullName>
    <label>Required Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Task__c/fields/Resource_Project__c.field-meta.xml
<CustomField>
    <fullName>Resource_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource-Project</label>
    <referenceTo>Resource_Project__c</referenceTo>
    <relationshipLabel>Custom Tasks</relationshipLabel>
    <relationshipName>Custom_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uninitiated</fullName>
                <default>true</default>
                <label>Uninitiated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource-Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource-Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource-Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Custom_Task__c.field-meta.xml
<CustomField>
    <fullName>Custom_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Task</label>
    <referenceTo>Custom_Task__c</referenceTo>
    <relationshipLabel>Resource-Projects</relationshipLabel>
    <relationshipName>Resource_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>resource linked to the project</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Assign_Task.cls
public with sharing class Assign_Task {
    
    
    //Trae las custom task pendientes para un resource-project y las retorna.
    public static Map<String,List<Custom_Task__c>> getCustomTask(){
        
        //obtener el id del usuario logueado.
        Id userId = UserInfo.getuserId();
        
        // traer los resources project cuya lookup sera UserId
        List<Resource_Project__c>resource_project_linked=[SELECT Id, Resource__c 
                                                          FROM Resource_Project__c 
                                                          WHERE Resource__c=:userId];
        
        // System.debug(resource_project_linked);
        // iterar la lista y poner los id en un set.
        Set<Id> resources_project_id=new Set<Id>();
        for(Resource_Project__c item:resource_project_linked){
            resources_project_id.add(item.id);
        }
        List<Custom_Task__c> getTask=[Select Id,Name,Status__c,Project_Name__c,Resource_Project__c,Required_Hours__c,Registered_Hours__c
                                      FROM Custom_Task__c 
                                      WHERE Status__c!='Completed' 
                                      AND Resource_Project__c IN:resources_project_id  order by Status__c DESC];
        
        //
        Map<String,List<Custom_Task__c>> taskByProject= new Map<String,List<Custom_Task__c>>(); 
        
        for(Custom_Task__c task:getTask){
            if(!taskByProject.containsKey(task.Project_Name__c)){
                taskByProject.put(task.Project_Name__c,new List<Custom_Task__c>());
                taskByProject.get(task.Project_Name__c).add(task);
            }
            else{
                taskByProject.get(task.Project_Name__c).add(task);
            }
        }
        
        return taskByProject;
        
    }
    //cuenta la cantidad de tareas pendientes por resource-project
    public static Map<String,Integer> countPendingTask(){
        Map<String,Integer> pendigTaskByProject= new Map<String,Integer>();
        
        Map<String,List<Custom_Task__c>> customTaskByProject=getCustomTask();
        
        List<Custom_Task__c> customTaskList= new List<Custom_Task__c>();
        for(List<Custom_Task__c> taskList : customTaskByProject.values()){
            for(Custom_Task__c task :taskList ){
                customTaskList.add(task);
            }
        }
        for(Custom_Task__c task : customTaskList){
            
           if(!pendigTaskByProject.containsKey(task.Project_Name__c)){
         pendigTaskByProject.put(task.Project_Name__c,customTaskByProject.get(task.Project_Name__c).size());
           }
        }
       return pendigTaskByProject;
    }
    // devuelve el nombre del projecto al que pertenece la tarea.
    //public static String getProjectName( ){
    // return getCustomTask()[0].Project_Name__c;
    // }
    // actualiza el campo Registered_Hours__c en la base de datos.
    public static void setRegisteredHours(Id custom_task,Integer hours_Registered){
        Custom_Task__c task=[SELECT id,Registered_Hours__c 
                             FROM Custom_Task__c 
                             WHERE id=:custom_task];
  
        
        if(task.Registered_Hours__c==NULL){
            task.Registered_Hours__c=hours_Registered;
        }
        else{
            task.Registered_Hours__c+=hours_Registered;
        }
        
        update task;
      
    }
    // cambia el status de la custom task a 'In Progress'ó'completed'
    // y lo actualiza en la base de datos.
    public static void change_Status(Id custom_task,String status){
        Custom_Task__c task=[SELECT id, Status__c 
                             FROM Custom_Task__c 
                             WHERE id=:custom_task];
        
        if(status=='Completed'||status=='In Progress' ){
            task.Status__c=status;
        }
        
        update task;
    }
    
}