force-app/main/default/objects/Custom_Task__c/Custom_Task__c.object-meta.xml
<CustomObject>
    <label>Custom Task</label>
    <nameField>
        <label>Custom Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project linked with the current de Resource Project</description>
    <formula>Resource_Project__r.Project__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Task__c/fields/Resource_Project__c.field-meta.xml
<CustomField>
    <fullName>Resource_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource-Project</label>
    <referenceTo>Resource_Project__c</referenceTo>
    <relationshipLabel>Custom Tasks</relationshipLabel>
    <relationshipName>Custom_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uninitiated</fullName>
                <default>true</default>
                <label>Uninitiated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
                <default>true</default>
                <label>Pre-Kickoff</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Project__c/Resource_Project__c.object-meta.xml
<CustomObject>
    <label>Resource-Project</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Resource-Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource-Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project__c/fields/Custom_Task__c.field-meta.xml
<CustomField>
    <fullName>Custom_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Task</label>
    <referenceTo>Custom_Task__c</referenceTo>
    <relationshipLabel>Resource-Projects</relationshipLabel>
    <relationshipName>Resource_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>project to which the resource is assigned</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resource-Projects</relationshipLabel>
    <relationshipName>Resource_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>resource linked to the project</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectValidation.cls
public class ProjectValidation {
    
    public static void getValidation(List<Project__c> project_updated){
        // Se realiza una query que traiga los Resources_project asociados a ese Id de Project.
        List<Resource_Project__c> asignatedResources=[SELECT Id ,Project__c ,Resource__c
                                                      From Resource_Project__c 
                                                      where Project__c IN : project_updated];
        
        
    
        // pedir solo las tareas con status in progress
        List<Custom_Task__c> task_Resource=[SELECT Id,Resource_Project__c,Status__c 
                                            FROM Custom_Task__c 
                                            WHERE Resource_Project__c IN:asignatedResources];
        
        
        //Se crea una lista de tipo Set donde se guardaran los id de Resources.
        Set<Id> resourcesId=new Set<Id>();
        //Se itera la lista de Resource_Project y se guarda el id de la lookup de Resource__c.
        for(Resource_Project__c teamMember:asignatedResources){
            resourcesId.add(teamMember.Resource__c);
            
        }
        //Si el Squad Lead no es null y no coincide con la lista de Resources_Project asignado,
        //Entonces no pertenece al Projecto y por lo tanto se debe lanzar el addError.
        if(project_updated[0].Squad_Lead__c!=null &&!resourcesId.contains(project_updated[0].Squad_Lead__c)){
            project_updated[0].addError('the selected Squad leader is not assigned to this project. Select a resource that has been assigned to the same project.');
           
        }
        //System.debug(task_Resource);
        for(Custom_Task__c task:task_Resource){
            if(project_updated[0].Status__c=='Completed'&& task.Status__c!='Completed' ){
                project_updated[0].addError('the project cannot change its status to completed until all assigned tasks are complete');
               
            }
            
        }
    }

}