force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Amount__c</fullName>
    <label>Opportunity Amount</label>
    <summarizedField>Opportunity_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Opportunity_Line_Item__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <summarizedField>Opportunity_Line_Item__c.Hours_Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Line_Item__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>Opportunity Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
                <default>true</default>
                <label>Pre-Kickoff</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <summarizedField>Project_Line_Item__c.Hours_Quantity__c</summarizedField>
    <summaryForeignKey>Project_Line_Item__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/Opp_CloseWon_Project_created_Test.cls
@isTest
public class Opp_CloseWon_Project_created_Test {
   
  public static Map<Id, List<Opportunity_Line_Item__c>> oppLineItemsByOppId = new Map<Id, List<Opportunity_Line_Item__c>>();
  
   @TestSetup
  static void makeData() {
    //create dates
    Date closeDate = Date.today().addDays(30);
    Date startDate = Date.today().addDays(10);
    Date endDate = Date.today().addDays(15);

    //create Accounts
    List<Account> accList = new List<Account>();
    for (Integer i = 0; i < 3; i++) {
      accList.add(new Account(Name = 'Test Account' + i));
    }
    insert accList;

    //create a opportunitys
    List<Opportunity> oppsToInsert = new List<Opportunity>();
    for (Integer i = 0; i < 3; i++) {
      Opportunity opp = new Opportunity(
        Name = 'Test Example Opportunity' + i,
        StageName = 'Prospecting',
        CloseDate = closeDate,
        Start_Date__c = startDate,
        End_Date__c = endDate,
        AccountId = accList[i].Id
      );
      oppsToInsert.add(opp);
    }
    insert oppsToInsert;

    //Create Opportunity Line Items
    List<Opportunity_Line_Item__c> oliList = new List<Opportunity_Line_Item__c>();

    for (Integer i = 0; i < 3; i++) {
      oliList.add(
        new Opportunity_Line_Item__c(
          Hours_Quantity__c = 10,
          Opportunity__c = oppsToInsert[0].id,
          Rol__c = 'Project Manager',
          Amount__c = 1000
        )
      );
    }
    insert oliList;
    oppLineItemsByOppId.put(oppsToInsert[0].id, oliList);
  }

  ////////////////////////////Test method///////////////////////////////////

  @isTest
  private static void ProjectCreatedTest() {
    List<Opportunity> oppttyList = [
      SELECT
        Id,
        Name,
        Start_Date__c,
        End_Date__c,
        StageName,
        Opportunity_Amount__c
      FROM Opportunity
    ];
    List<Id> oppIds = new List<Id>();

    Test.startTest();
    for (Opportunity op : oppttyList) {
      op.StageName = 'Closed Won';
      oppIds.add(op.Id);
    }
    update oppttyList;
    Test.stopTest();

    //when opp is closedWon, create a new project register.
    List<Project__c> projectList = [
      SELECT
        Id,
        Name,
        Opportunity__c,
        Start_Date__c,
        End_Date__c,
        Status__c,
        Total_Hours__c,
        Amount__c
      FROM Project__c
      WHERE Opportunity__c IN :oppIds
    ];

    //Number of created Projects must be 3
    System.assertEquals(
      3,
      projectList.size(),
      'Number of created Projects must be 3'
    );
    for (Integer i = 0; i < 3; i++) {
      //check the correct Relationship of project to opportunity
      System.assertEquals(
        oppIds[i],
        projectList[i].Opportunity__c,
        'Incorrect relatioship of Project__c to Opportunity Object'
      );
      //check Correct Dates
      System.assertEquals(
        Date.today().addDays(10),
        projectList[i].Start_Date__c,
        'Incorrect start date!, must be ' + oppttyList[i].Start_Date__c
      );
      System.assertEquals(
        Date.today().addDays(15),
        projectList[i].End_Date__c,
        'Incorrect End date!, must be ' + oppttyList[i].End_Date__c
      );

      //Check origin of opportunity, Stage of this must be 'Closed Won'
      System.assertEquals(oppttyList[i].StageName, 'Closed Won');

      //Check start Status of projects
      System.assertEquals('Pre-Kickoff', projectList[i].Status__c);
    }
    //Check correct Rollup Summary of data
    System.assertEquals(
      oppttyList[0].Opportunity_Amount__c,
      3000,
      'Rollup Summary must be 3000'
    );
    System.assertEquals(
      projectList[0].Amount__c,
      3000,
      'Rollup Summary must be 3000'
    );
    System.assertEquals(
      projectList[0].Total_Hours__c,
      30,
      'Rollup Summary must be 30'
    );
  }
}